### ISSUE TITLE
Quotes break highlighting

### ISSUE THREAD

**Issue by michaelmior** [treycordova/rustpeg.vim#1]
Thanks so much for this! Overall works great :) However, if I have a rule like the following, the script seems to think the rest of the file after the `"` is part of a string literal.

```
nonquote -> String                                                                                                                                  
    = [^"] { match_str.to_string() }
```

**Comment by treycordova** [comment]
I can't seem to reproduce this issue. Is that the only rule in your `.rustpeg` file? I think it might help to see the surrounding rules as well.

**Comment by michaelmior** [comment]
Sorry, I should have checked that this example reproduced the issue on its own. Try the following

```
quote
  = "\""

nonquote -> String
    = [^"] { match_str.to_string() }
```

**Comment by treycordova** [comment]
Try this out: https://github.com/treycordova/rustpeg.vim/commit/bdb20d33322eb4ea3d96545988210f5f0c583049.

**Comment by michaelmior** [comment]
@treycordova Thanks! That does fix that specific issue. However, I noticed that adding a `use` declaration with braces at the top of the file (example below) still has the same issue.

```
use super::{A};

quote
  = "\""

nonquote -> String
    = [^"] { match_str.to_string() }
```

**Comment by treycordova** [comment]
There are some oddities around Rust regions that still exist, but this should help in the meantime.

See https://github.com/treycordova/rustpeg.vim/commit/7100fbe0e8452eebd462ef49b6d35cb0814376e0.

**Comment by michaelmior** [comment]
Awesome! This seems to work as expected :) Thanks!
